version: "3.7"

networks:
  net:
    driver: overlay
    attachable: true
    name: DB_net
  work:
    driver: overlay
    attachable: true
    name: DB_work

services:
  mariadb:
    image: mariadb:latest
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ./.mysql_backup:/var/lib/mysql
    networks:
      - net
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}

  workdb:
    image: mariadb:latest
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ./.work_backup:/var/lib/mysql
    networks:
      - work
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}

  postgres:
    image: postgres
    env_file:
      - ./.env
    networks:
      - work
      - net
    environment:
      POSTGRES_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}

  adminer:
    image: adminer:latest
    volumes:
      - ./adminer/adminer.css:/var/www/html/adminer.css
      - ./adminer/custom_design:/var/www/html/custom_design
      - ./adminer/plugins:/var/www/html/plugins-enabled
    networks:
      - net
      - work
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        - traefik.http.routers.adminer.entrypoints=websecure
        - traefik.http.routers.adminer.rule=Host(`adminer.nas.hyeon.pro`)
        - traefik.http.routers.adminer.tls.certresolver=leresolver
        - traefik.http.services.adminer.loadbalancer.server.port=8080
  # redis:
  #   image: redis:latest
  #   volumes:
  #     - ./.redis:/data
  #   networks:
  #     - work
  #     - net
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.role == manager
